spring:
  application:
    name: Gateway_1
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8070
          predicates:
            - Path=/api/users/**
          filters:
            - Filtration
        - id: security
          uri: http://localhost:8080
          predicates:
            - Path=/auth/users/**






server:
  port: 8222


