version: '3'
services:
  database1:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - datauser:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  datauser:
    driver: local