spring:
  application:
    name: User_management
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/users
    username: postgres
    password: hamza
server:
  port: 8070
jwt:
  secret: "U29tZVN1cGVyU2VjdXJlS2V5Rm9yTXlKd3RBdXRoZW50aWNhdGlvbg=="